import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isMobile = width < 768;
const isNarrowMobile = width <= 430;

export const contactStyles = StyleSheet.create({
  contactSection: {
    backgroundColor: '#ffffff',
    paddingVertical: 60,
    paddingHorizontal: 20,
    width: '100%',
    alignItems: 'center',
  },
  contactTitle: {
    fontSize: 32,
    fontWeight: '700',
    marginBottom: 8,
    color: '#212529',
  },
  contactSubtitle: {
    fontSize: 16,
    color: '#6c757d',
    marginBottom: 32,
    lineHeight: 24,
  },
  form: {
    width: '100%',
    maxWidth: 1200,
  },
  formGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: '#212529',
  },
  input: {
    borderWidth: 1,
    borderColor: '#dee2e6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
  },
  inputFocused: {
    borderColor: '#0d6efd',
    shadowColor: '#0d6efd',
    shadowOpacity: 0.1,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  submitButton: {
    backgroundColor: '#0d6efd',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    shadowColor: '#0d6efd',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  submitButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
  },
  // New styles for name row and phone number
  nameRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  halfWidth: {
    flex: 1,
  },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  countryCodeInput: {
    borderWidth: 1,
    borderColor: '#dee2e6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#ffffff',
    minWidth: 80,
    textAlign: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  phoneInput: {
    flex: 1,
  },
  // Captcha styles
  captchaContainer: {
    flexDirection: isMobile ? 'column' : 'row',
    alignItems: 'stretch',
    gap: isMobile ? 8 : 12,
  },
  captchaQuestion: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    paddingHorizontal: isMobile ? 18 : 16,
    paddingVertical: isMobile ? 16 : 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dee2e6',
    flex: 1,
    minHeight: isMobile ? 50 : 'auto',
  },
  captchaQuestionText: {
    fontSize: isMobile ? 18 : 16,
    fontWeight: '600',
    color: '#212529',
    flex: 1,
    lineHeight: isMobile ? 24 : 20,
  },
  refreshCaptcha: {
    marginLeft: isMobile ? 12 : 8,
    padding: isMobile ? 8 : 4,
    backgroundColor: '#e9ecef',
    borderRadius: 6,
    minWidth: isMobile ? 40 : 'auto',
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshCaptchaText: {
    fontSize: isMobile ? 18 : 16,
  },
  captchaInput: {
    borderWidth: 1,
    borderColor: '#dee2e6',
    borderRadius: 8,
    paddingHorizontal: isMobile ? 16 : 12,
    paddingVertical: isMobile ? 16 : 12,
    fontSize: isMobile ? 18 : 16,
    backgroundColor: '#ffffff',
    minWidth: isMobile ? 100 : 80,
    textAlign: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    minHeight: isMobile ? 50 : 'auto',
  },
  // Error and Success Message Styles
  errorContainer: {
    backgroundColor: '#f8d7da',
    borderWidth: 1,
    borderColor: '#f5c6cb',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
    width: '100%',
  },
  errorText: {
    color: '#721c24',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  successContainer: {
    backgroundColor: '#d4edda',
    borderWidth: 1,
    borderColor: '#c3e6cb',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
    width: '100%',
  },
  successText: {
    color: '#155724',
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
});