import { StyleSheet, Platform, Dimensions } from 'react-native';

const isWeb = Platform.OS === 'web';
const { width, height } = Dimensions.get('window');
const isMobile = width < 768; // Mobile breakpoint

export const heroStyles = StyleSheet.create({
  hero: {
    minHeight: isWeb ? height * 0.9 : 800,
    width: '100%',
    ...(isWeb && { marginTop: 60 }),
  },
  overlay: {
    flex: 1,
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  heroContent: {
    maxWidth: 1200,
    ...(isWeb && { marginHorizontal: 'auto' as any }),
  },
  section: {
    marginBottom: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 24,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionContent: {
    marginBottom: 30,
    paddingHorizontal: 0,
  },
  sideHeading: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0d6efd',
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#0d6efd',
    paddingLeft: 12,
  },
  contentText: {
    fontSize: 18,
    color: '#212529',
    lineHeight: 26,
    marginBottom: 16,
    textAlign: 'justify',
  },
  imageSection: {
    alignItems: 'center',
    marginBottom: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  imageSectionContent: {
    alignItems: 'center',
    marginBottom: 30,
    paddingHorizontal: 0,
  },
  pledgeImage: {
    width: isWeb ? 400 : width * 0.8,
    height: isWeb ? 300 : 200,
    borderRadius: 8,
  },
  carouselContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 20,
    backgroundColor: 'rgba(248, 249, 250, 0.9)',
    borderRadius: 12,
    padding: 16,
  },
  carouselNav: {
    backgroundColor: '#0d6efd',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0d6efd',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  navText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  carouselContent: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  carouselImage: {
    width: isWeb ? 250 : width * 0.5,
    height: isWeb ? 180 : 120,
    borderRadius: 8,
    marginBottom: 12,
  },
  carouselTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#212529',
    textAlign: 'center',
  },
  indicatorContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    gap: 8,
  },
  indicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(13, 110, 253, 0.3)',
  },
  activeIndicator: {
    backgroundColor: '#0d6efd',
  },
  heroButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'center',
    marginTop: 30,
  },
  primaryButton: {
    backgroundColor: '#0d6efd',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 8,
    shadowColor: '#0d6efd',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
  },
  secondaryButton: {
    borderWidth: 2,
    borderColor: '#ffffff',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
  },
  secondaryButtonText: {
    color: '#0d6efd',
    fontWeight: '600',
    fontSize: 16,
  },
  // Placeholder styles for development
  pledgeImagePlaceholder: {
    width: isWeb ? 400 : width * 0.8,
    height: isWeb ? 300 : 200,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#dee2e6',
    borderStyle: 'dashed',
  },
  placeholderText: {
    fontSize: 48,
    marginBottom: 8,
  },
  placeholderLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
  },
  placeholderSubtext: {
    fontSize: 12,
    color: '#6c757d',
    textAlign: 'center',
  },
  carouselImagePlaceholder: {
    width: isWeb ? 250 : width * 0.5,
    height: isWeb ? 180 : 120,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#dee2e6',
    borderStyle: 'dashed',
  },
  carouselPlaceholderIcon: {
    fontSize: 48,
    color: '#0d6efd',
  },
  carouselSubtext: {
    fontSize: 10,
    color: '#6c757d',
    textAlign: 'center',
    marginTop: 4,
  },
  // Auto-carousel styles
  autoCarouselContainer: {
    backgroundColor: 'rgba(248, 249, 250, 0.9)',
    borderRadius: 12,
    padding: 20,
    marginVertical: 20,
    minHeight: isWeb ? 400 : 'auto',
    flexDirection: isMobile ? 'column' : 'row', // Row for desktop, column for mobile
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 3,
  },
  carouselImageContainer: {
    width: isMobile ? '100%' : '50%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: isMobile ? 20 : 0,
    marginRight: isMobile ? 0 : 20,
  },
  autoCarouselImage: {
    width: isWeb ? 400 : width * 0.85,
    height: isWeb ? 320 : 250,
    borderRadius: 12,
  },
  carouselTextContainer: {
    width: isMobile ? '100%' : '50%',
    justifyContent: 'center',
    alignItems: isMobile ? 'center' : 'flex-start',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  autoCarouselTitle: {
    fontSize: isWeb ? 24 : 20,
    fontWeight: '700',
    color: '#212529',
    marginBottom: 12,
    textAlign: isMobile ? 'center' : 'left',
    width: '100%',
  },
  carouselDescription: {
    fontSize: isWeb ? 16 : 14,
    color: '#6c757d',
    lineHeight: isWeb ? 24 : 22,
    textAlign: isMobile ? 'center' : 'left',
    width: '100%',
    maxWidth: isWeb ? 500 : '100%',
  },
  // Carousel navigation dots
  carouselDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  carouselDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#dee2e6',
    marginHorizontal: 4,
  },
  carouselDotActive: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#0d6efd',
    marginHorizontal: 4,
  },
});